# Generated by Django 4.1 on 2023-01-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("user_pw", models.CharField(max_length=50)),
                ("user_name", models.CharField(max_length=50)),
                ("date_joined", models.DateTimeField()),
            ],
        ),
    ]
