# Generated by Django 4.1 on 2023-01-06 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file", "0001_initial"),
        ("secondapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detail",
            name="name",
        ),
        migrations.AddField(
            model_name="detail",
            name="content",
            field=models.ManyToManyField(to="file.mbtidata"),
        ),
    ]
