# Generated by Django 4.1 on 2023-01-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_post_updated_at_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
